name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [12, 11, 10.15]

    runs-on: macos-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v3

      - run: ./test.sh
