name: publish

on:
  workflow_dispatch

jobs:
  publish:
    runs-on: macos-10.15

    env:
      MACOSX_DEPLOYMENT_TARGET: 10.15
      ACLOCAL_PATH: /usr/local/share/aclocal
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }} 
      PKG_NAMES: aria2 axel bash bat bison bmake bzip2 cmake coreutils cppcheck ctop curlie curl darkhttpd diffutils dos2unix ed file findutils flex gawk git glow gm4 gmake gnupg gh gn gogs gotop gotty gperf grep gsed gtar gzip hugo jq lazygit libarchive lzip lz4 mediainfo mosh mpg123 nasm ninja nushell openssl patchelf patch pkg-config pngquant putty pigz qpdf quickjs rtmpdump sqlite starship tcpdump tealdeer tig tmux tree uctags unrar unzip uppm util-linux volta wget xmake xxd xz yasm youtubedr yq zopfli zip p7zip zstd

    steps:
      - run: brew uninstall go@1.17

      - run: wget https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
      - run: chmod a+x ppkg
      - run: ./ppkg setup --use-system-package-manager
      - run: ./ppkg update
      - run: |
          for PKG_NAME in $PKG_NAMES
          do
            ./ppkg install $PKG_NAME --link-type=static-prefered --install-lib=static
            ./ppkg pack    $PKG_NAME
          done

      - run: git config --global --add safe.directory /__w/uppm-package-repository-macos-x86_64/uppm-package-repository-macos-x86_64
      - run: git config --global user.name  leleliu008
      - run: git config --global user.email leleliu008@gmail.com

      - uses: actions/checkout@v3

      - run: rm -rf package/*
      - run: mv -v /opt/ppkg/cache.d/bin/* package/

      - run:  ./test.sh

      - run: git add package
      - run: git commit -m "new release"
      - run: git push origin master

      - run: printf '%s\n' "$RELEASE_TOKEN" | gh auth login --with-token

      - run: ./publish.sh
